language: php
 
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
 
allow_failures:
    - php: hhvm

before_script:
  - composer install

script: vendor/bin/phpunit --coverage-text ./test
 
cache:
  directories:
    - $COMPOSER_CACHE_DIR
